// This is an autogenerated file from Firebase Studio. Do not edit.
"use client";

import * as React from "react";
import { useParams } from "next/navigation";
import { getFirestore, doc, getDoc } from "firebase/firestore";
import { getFunctions, httpsCallable } from "firebase/functions";
import { useAuth } from "@/hooks/use-auth";
import type { Bet } from "@/types";
import { getFirebaseApp } from "@/lib/firebase";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";
import { BetChallengeCard } from "@/components/bet-challenge-card";

export default function BetChallengePage() {
  const params = useParams();
  const { betId } = params;
  const { user, loading: authLoading } = useAuth();
  const { toast } = useToast();

  const [bet, setBet] = React.useState<Bet | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [isAccepting, setIsAccepting] = React.useState(false);

  React.useEffect(() => {
    if (typeof betId !== "string") return;

    const fetchBet = async () => {
      setLoading(true);
      setError(null);
      try {
        const db = getFirestore(getFirebaseApp());
        const betRef = doc(db, "bets", betId);
        const betSnap = await getDoc(betRef);

        if (betSnap.exists()) {
          setBet({ id: betSnap.id, ...betSnap.data() } as Bet);
        } else {
          setError("Bet not found.");
        }
      } catch (err) {
        console.error("Error fetching bet:", err);
        setError("Failed to load bet details.");
      } finally {
        setLoading(false);
      }
    };

    fetchBet();
  }, [betId]);

  const handleAcceptBet = async () => {
    if (!user || !bet) return;
    setIsAccepting(true);

    const functions = getFunctions();
    const acceptBet = httpsCallable(functions, "acceptBet");

    try {
      const result: any = await acceptBet({ betId: bet.id });
      if (result.data.success) {
        toast({
          title: "Bet Accepted!",
          description: "The challenge has been matched. Good luck!",
        });
        // Refresh bet data
        const db = getFirestore(getFirebaseApp());
        const betRef = doc(db, "bets", bet.id);
        const betSnap = await getDoc(betRef);
        if (betSnap.exists()) {
          setBet({ id: betSnap.id, ...betSnap.data() } as Bet);
        }
      } else {
        throw new Error(result.data.error || "Failed to accept bet.");
      }
    } catch (err: any) {
      console.error("Error accepting bet:", err);
      toast({
        title: "Error",
        description: err.message || "An unexpected error occurred.",
        variant: "destructive",
      });
    } finally {
      setIsAccepting(false);
    }
  };

  const handleShareBet = async () => {
    if (!bet) return;
    const shareData = {
      title: 'Playcer Bet Challenge',
      text: `I've challenged someone to a bet on ${bet.away_team} vs ${bet.home_team}. Do you have what it takes to accept?`,
      url: window.location.href,
    };
    try {
      if (navigator.share) {
        await navigator.share(shareData);
        toast({ title: 'Challenge shared!' });
      } else {
         navigator.clipboard.writeText(window.location.href);
         toast({ title: "Link Copied!", description: "Challenge link copied to clipboard." });
      }
    } catch (error) {
      console.error('Error sharing bet:', error);
      toast({
        title: 'Sharing failed',
        description: 'Could not share the challenge at this time.',
        variant: 'destructive',
      });
    }
  };

  const renderContent = () => {
    if (loading || authLoading) {
      return (
        <div className="w-full max-w-2xl">
          <Skeleton className="h-[400px] w-full rounded-lg" />
        </div>
      );
    }

    if (error) {
      return <p className="text-destructive">{error}</p>;
    }

    if (bet) {
      return (
        <BetChallengeCard
          bet={bet}
          currentUser={user}
          onAccept={handleAcceptBet}
          onShare={handleShareBet}
          isAccepting={isAccepting}
        />
      );
    }

    return null;
  };

  return (
    <main className="flex min-h-screen w-full flex-col items-center justify-center p-4 bg-gray-50 dark:bg-gray-900">
        {renderContent()}
    </main>
  );
}
