// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Users, Swords, DollarSign } from "lucide-react";
import { UserManagementTable } from "@/components/admin/user-management-table";
import { AdminLayout } from "@/components/admin/admin-layout";

export default function AdminDashboardPage() {
  const { user, claims, loading } = useAuth();
  const router = useRouter();
  const [isAdmin, setIsAdmin] = useState(false);

  useEffect(() => {
    if (!loading) {
      if (!user) {
        router.push("/signin");
      } else if (claims && claims.admin === true) {
        setIsAdmin(true);
      } else {
        router.push("/dashboard");
      }
    }
  }, [user, claims, loading, router]);

  if (loading || !isAdmin) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen p-4">
        <div className="w-full max-w-4xl space-y-8">
            <h1 className="text-2xl font-bold text-center">Verifying Access...</h1>
            <Skeleton className="h-40 w-full" />
            <Skeleton className="h-64 w-full" />
        </div>
      </div>
    );
  }

  const stats = {
      totalUsers: 1482,
      totalBetsMatched: 731,
      platformRevenue: 12450.75,
  };

  return (
    <AdminLayout>
        <header className="mb-8">
            <h1 className="text-4xl font-headline font-black">Admin Dashboard</h1>
            <p className="text-muted-foreground">Welcome, {user?.displayName || 'Admin'}.</p>
        </header>
        
        <div className="grid gap-4 md:grid-cols-3 mb-8">
            <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Total Users</CardTitle>
                    <Users className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                    <div className="text-2xl font-bold">{stats.totalUsers.toLocaleString()}</div>
                </CardContent>
            </Card>
             <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Bets Matched</CardTitle>
                    <Swords className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                    <div className="text-2xl font-bold">{stats.totalBetsMatched.toLocaleString()}</div>
                </CardContent>
            </Card>
             <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Platform Revenue</CardTitle>
                    <DollarSign className="h-4 w-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                    <div className="text-2xl font-bold">${stats.platformRevenue.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                </CardContent>
            </Card>
        </div>

        <UserManagementTable />
    </AdminLayout>
  );
}
