// This is an autogenerated file from Firebase Studio. Do not edit.
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Twitter } from "lucide-react";

import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { getFirebaseAuth, getTwitterProvider } from "@/lib/firebase";
import { signInWithPopup } from "firebase/auth";

export function LoginButton() {
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();
  const router = useRouter();

  const handleSignIn = async () => {
    setIsLoading(true);
    try {
      const auth = getFirebaseAuth();
      const provider = getTwitterProvider();
      await signInWithPopup(auth, provider);
      // On successful sign-in, redirect to the dashboard.
      router.push("/dashboard");
    } catch (error: any) {
      console.error("Authentication error:", error);
      let description = "An unexpected error occurred. Please try again.";
      if (error.code === 'auth/popup-closed-by-user') {
        description = "You closed the sign-in window. Please try again.";
      } else if (error.code === 'auth/cancelled-popup-request') {
        description = "The sign-in process was cancelled. Please try again.";
      }
      toast({
        title: "Login Failed",
        description,
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Button
      onClick={handleSignIn}
      disabled={isLoading}
      style={{ backgroundColor: '#00c3ff' }}
    >
      <Twitter className="mr-2 h-4 w-4" />
      {isLoading ? "Redirecting..." : "Login with Twitter"}
    </Button>
  );
}
