// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuth } from "@/hooks/use-auth";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AdminLayout } from "@/components/admin/admin-layout";
import { DisputeResolutionTable } from "@/components/admin/dispute-resolution-table";
import { Gavel } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

export default function DisputeResolutionPage() {
  const { user, claims, loading } = useAuth();
  const router = useRouter();
  const [isAdmin, setIsAdmin] = useState(false);

  useEffect(() => {
    if (!loading) {
      if (!user) {
        router.push("/signin");
      } else if (claims && claims.admin === true) {
        setIsAdmin(true);
      } else {
        router.push("/dashboard");
      }
    }
  }, [user, claims, loading, router]);
  
   if (loading || !isAdmin) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen p-4">
        <div className="w-full max-w-4xl space-y-8">
            <h1 className="text-2xl font-bold text-center">Verifying Access...</h1>
            <Skeleton className="h-40 w-full" />
            <Skeleton className="h-64 w-full" />
        </div>
      </div>
    );
  }

  return (
    <AdminLayout>
      <header className="mb-8 flex items-center gap-4">
        <Gavel className="size-10 text-primary" />
        <div>
            <h1 className="text-4xl font-headline font-black">Dispute Resolution</h1>
            <p className="text-muted-foreground">Review and resolve user-submitted bet disputes.</p>
        </div>
      </header>
      
      <DisputeResolutionTable />
    </AdminLayout>
  );
}
